- name: Установка Docker
  block:
  - name: install prerequisites for Docker repository
    become: true
    ansible.builtin.apt:
      pkg:
      - ca-certificates
      - curl
      - gnupg2
      - lsb-release

  - name: add docker apt key
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker apt repo
    become: true
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
      state: present
      update_cache: yes

  - name: install docker and its dependencies
    become: true
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-compose
      state: present

  - name: start and enable docker daemon
    become: true
    service:
      name: docker
      state: started
      enabled: yes

  - name: start and enable containerd daemon
    become: true
    service:
      name: containerd
      state: started
      enabled: yes


