version: "3"
services:
  app:
    container_name: app
    build:
      context: .
    image: app:latest
    restart: always
    ports:
      - 80:80
    networks:
      - myNetwork
  api:
    build:
      context: .
    image: json-server:latest
    restart: always
    container_name: api
    ports:
      - 8000:8000
    networks:
      - myNetwork
networks:
  myNetwork:
    driver: bridge